import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { pinyin } from "pinyin-pro";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "../src/gb2312.ts");
const decoder = new TextDecoder("gb18030");
const SIMPLE_EXCLUDED_PARTS =
  /(zh|ch|sh|ang|eng|ing|ong|iang|uang|iong|uai|iao|ian|uan|van|vn|ve)/;

const toInputPinyin = (value) =>
  value.toLowerCase().replaceAll("ü", "v").replace(/[^a-z0-9]/g, "");

const isSimplePinyin = (value) =>
  value.length <= 3 && !SIMPLE_EXCLUDED_PARTS.test(value);

const records = [];
const seen = new Set();

for (let high = 0xb0; high <= 0xf7; high += 1) {
  for (let low = 0xa1; low <= 0xfe; low += 1) {
    const char = decoder.decode(Buffer.from([high, low]));

    if (!/[\u4e00-\u9fff]/u.test(char) || seen.has(char)) {
      continue;
    }

    seen.add(char);

    const marked = pinyin(char, { toneType: "symbol", type: "array" })[0];
    const plain = pinyin(char, { toneType: "none", type: "array" })[0];
    const answer = toInputPinyin(plain);

    if (!marked || !answer) {
      throw new Error(`Missing pinyin for ${char}`);
    }

    records.push({
      answer,
      char,
      marked,
      simple: isSimplePinyin(answer)
    });
  }
}

const simple = records.filter((record) => record.simple);
const complex = records.filter((record) => !record.simple);

const tupleLines = (items) =>
  items
    .map(
      (item) =>
        `  [${JSON.stringify(item.char)}, ${JSON.stringify(
          item.marked
        )}, ${JSON.stringify(item.answer)}]`
    )
    .join(",\n");

const file = `// Generated by scripts/generate-gb2312.mjs. Do not edit by hand.
export type Gb2312Record = readonly [
  char: string,
  markedPinyin: string,
  answer: string
];

export const GB2312_SIMPLE: readonly Gb2312Record[] = [
${tupleLines(simple)}
];

export const GB2312_COMPLEX: readonly Gb2312Record[] = [
${tupleLines(complex)}
];

export const GB2312_ALL: readonly Gb2312Record[] = [
${tupleLines(records)}
];

export const GB2312_SIMPLE_COUNT = ${simple.length};
export const GB2312_COMPLEX_COUNT = ${complex.length};
export const GB2312_TOTAL_COUNT = ${records.length};
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, file, "utf8");

console.log(
  `Generated ${records.length} GB2312 characters: ${simple.length} simple, ${complex.length} complex.`
);
